/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (ToyStoryRacer)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8008819Cu
#define func_8008819C BootEntry  /* alias */
